### ISSUE TITLE
Remove strip_tags from email save routine

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-per-product-emails#11]
In the function where the receipt is saved (edd_ppe_edit_receipt), the strip_tags function is used. This removes any inline styles the site-owner may want in their email. This is different behaviour than EDD core emails. In EDD core, inline styles remain and tags are not stripped out. 

However, in Per Product emails, despite removing strip_tags from that function, if you switch from "text" to "visual", the tags are also removed there. This also does not happen in EDD core as you can switch from text to visual and tags remain (Downloads > Emails > New Sale Notifications).

**Comment by pippinsplugins** [comment]
@mintplugins try that

**Comment by mintplugins** [comment]
@pippinsplugins That's working perfectly for me here now. Thanks!
