### ISSUE TITLE
$license_key not defined upon checkout

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-per-product-emails#13]
In the edd_ppe_email_template_tags function function, it uses the variable $license_key without defining it - if you do not have Software Licensing active. This causes an error upon checkout if Software Licensing is not activated.

Notice: Undefined variable: license_key in /app/public/wp-content/plugins/edd-per-product-emails/includes/email-functions.php on line 326

**Comment by SDavisMedia** [comment]
@mintplugins I can't seem to replicate this. Can you lay out some configuration guidelines? It doesn't seem to be happening on my end.

**Comment by mintplugins** [comment]
@SDavisMedia For sure I should have left those here. 

1. Make sure Software Licensing is not activated. 

2. Set up a product. 

3. Set up a per-product-email for that product so it is sent to the user upon purchase. 

3. Purchase the product.

4. Error message should show upon purchase.

**Comment by SDavisMedia** [comment]
That's definitely what I've been doing. Hmmm...

**Comment by SDavisMedia** [comment]
Oh there it is... an email is `inactive` by default after it's created. That's goofy. Replicated. Testing now.

**Comment by SDavisMedia** [comment]
Confirmed fixed for me on `issue/13`.

**Comment by mintplugins** [comment]
@SDavisMedia Awesome 👍 

That is a little strange to have it default to inactive.
