### ISSUE TITLE
Multiple purchase receipts on variable pricing - multi-option purchase mode.

### ISSUE THREAD

**Issue by dipakcg** [easydigitaldownloads/edd-per-product-emails#15]
Users receive multiple purchase receipts for the products that's been set with variable pricing - multi-option purchase mode.

**Product page with multi-option purchase mode**

![Product page with multi-option purchase mode](https://cldup.com/ztu_ahjiKz.png)

Here when users checkout and complete the order, PPE sends custom email 3 times. It should be sent single time only like default email.

**Comment by sumobi** [comment]
Merged into master
