### ISSUE TITLE
emails sending with Manual Purchases setting to not send emails

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-per-product-emails#17]
In Manual Purchases, you can create a payment and select not to send a receipt to the customer. PPE emails for a "purchased" product still send, though. We should stop that from happening.

**Comment by sumobi** [comment]
👍 I think this is more suited (and much easier) as a change to Manual Purchases. PR: https://github.com/easydigitaldownloads/edd-manual-purchases/issues/55
