### ISSUE TITLE
disable purchase receipt when resending from history page

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-per-product-emails#19]
Original customer report which describes the issue:

If you click the 'Resend Purchase Receipt' link which appears under the order email address on the Downloads -> Payment History listing, the per product email AND purchase receipt is sent even when the 'Disable purchase receipt' box is ticked in the Per Product Email settings. I would expect the Per Product Email to send, but not the purchase receipt.

I tested that and indeed if you use the Resend purchase receipt on the Payment History page it sends both the EDD receipt and the per product email.

**Comment by dipakcg** [comment]
As @misulicus stated, I've tried the same and it happens to me as well.

**Comment by cklosowski** [comment]
Fixed in #21
