### ISSUE TITLE
Warning: array_unique() expects parameter 1 to be array, null given in /edd-per-product-emails/includes/email-functions.php on line 98

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/edd-per-product-emails#22]
### Expected behavior

Customer has reported that when clicking to download a file, the following errors appear within per-product emails:

```
Warning: array_unique() expects parameter 1 to be array, null given in /home/willdogg/public_html/fromstudiotostage.com/wp-content/plugins/edd-per-product-emails/includes/email-functions.php on line 98

Warning: array_unique() expects parameter 1 to be array, null given in /home/willdogg/public_html/fromstudiotostage.com/wp-content/plugins/edd-per-product-emails/includes/email-functions.php on line 98

Warning: Invalid argument supplied for foreach() in /home/willdogg/public_html/fromstudiotostage.com/wp-content/plugins/edd-per-product-emails/includes/email-functions.php on line 100
```

Ticket located here: https://secure.helpscout.net/conversation/661184584/89946?folderId=180499

### Actual behavior
Triggers a PHP error and causes the download process to stop.

### Steps to reproduce the behavior

Customer reported the following:

`When I click the file, it takes a while to process and then it shows an error message that seems to be related to the per product emails extension (I've attached the error message below). If I click the file again a second time it downloads fine. I have a few extensions enabled. 1-I'm using the DB extension to upload and "serve" the files. 2-I'm restricting the download using Restrict Content Pro. 3-I have the free downloads extension and 3-obviously the per product emails option enabled. Just wondering what I can change to solve the per product email issue with the free downloads. Thanks so much! `

**Comment by cklosowski** [comment]
Just needs your review @mintplugins
