### ISSUE TITLE
Can't add attachments using payment_id

### ISSUE THREAD

**Issue by mtissington** [easydigitaldownloads/edd-per-product-emails#23]
Not sure if this is by neglect, by design or a bug ...

When a default receipt is sent a filter is called to add attachments - edd_receipt_attachments (which includes the payemnt_id as a parameter)

In edd-per-product-emails there does not appear to be an equivalent filter (I hope I'm just missing it).
Instead function edd_ppe_email_custom_purchase_receipts uses directly the new EDD email class to send an email which does not provide a filter to add attachments where the payment_id is available.

**Comment by cklosowski** [comment]
Confirmed, we need to include the `edd_receipt_attachments` filter, as it does in other areas when using `EDD_Emails` in the per product emails.

We then need to include them as the 4th argument for the call to send:
`EDD()->emails->send( $email, $subject, $message );`

Something as simple as this should work, as it is exactly what happens with the non-EDD_Emails call:
`$attachments = apply_filters( 'edd_receipt_attachments', array(), $payment_id, $payment_data );`

**Comment by cklosowski** [comment]
ready for your review @mintplugins

**Comment by mtissington** [comment]
I can confirm it works - thanks.

**Comment by cklosowski** [comment]
Thanks @mtissington I'll look at getting this update live in the very near future.
