### ISSUE TITLE
Use of deprectated postmeta for Software Licensing Key

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-per-product-emails#26]
### Expected behavior
When using Per Product Emails with Software licensing, a notice for a deprecated function should not be thrown.

### Actual behavior
A notice is thrown as it is still using the post meta call for Software Licensing in the `plugin-software-licenses.php` file within the `replace_license_key_email_tag_with_license_key` method.
```
		if ( $license ) {
			$license_key = get_post_meta( $license->ID, '_edd_sl_key', true );
		}else{
			$license_key = __( 'No License Key found.', 'edd-ppe' );
		}
```

### Steps to reproduce the behavior
1) Enable Per Product Emails and setup an email for a licensed product.
2) Purchase this product and view the email.
3) Verify the notice in the logs.

### Information:
PHP Version: All

EDD Per Product Emails Version (or branch): Latest

EDD Version (or branch): Latest

WordPress Version: All

**Comment by dgoldak** [comment]
Provided customer with the fix, no reports of issues.

https://secure.helpscout.net/conversation/1256367885/162936?folderId=1847242
