### ISSUE TITLE
Add a filter on the capability required to manage emails

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-per-product-emails#5]
Customer requested we add the ability to filter the capability required to access and manage the emails. I think this would be useful for shops that want someone to manage these emails without having access to everything else `manage_shop_settings` allows. Thoughts?

**Comment by pippinsplugins** [comment]
Makes sense to me!

**Comment by sumobi** [comment]
@mindctrl there's now a `edd_ppe_capability_type` filter included, going out in v1.1
