### ISSUE TITLE
Emails with apostrophes are getting extra escaping.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-per-product-emails#6]
If you have an email set up with an apostrophe in the subject line, it is adding slashes every time you save. See screenshot:

<img width="1417" alt="screen shot 2016-01-26 at 12 49 21 pm" src="https://cloud.githubusercontent.com/assets/1638128/12589348/478ab42a-c42b-11e5-9f46-bc417fbea826.png">

**Comment by pippinsplugins** [comment]
@sumobi Could you grab this?

**Comment by sumobi** [comment]
@pippinsplugins :+1:
